/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'M355_SqrWaveVoltammetry' 
 * Target:  'ADuCM355' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "ADuCM355.h"



#endif /* RTE_COMPONENTS_H */
